#!/usr/bin/env python3
# Copyright 2026 Kevin Ahrendt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate vectors_data.c embedding tests/vectors/testvector*.bit as C arrays.

Run at CMake configure time (see main/CMakeLists.txt). The output defines the
QEMU_VECTORS table declared in qemu_vectors.h. If the vectors directory is empty
or missing, an empty table is emitted so the firmware still builds, and the
runner treats a zero-vector run as "skipped" rather than a failure.

Usage: embed_vectors.py <vectors_dir> <output.c>
"""

import os
import re
import sys


def c_symbol(name: str) -> str:
    """Turn a vector basename into a valid C identifier prefix."""
    return "vec_" + re.sub(r"[^0-9a-zA-Z_]", "_", name)


def emit_array(out, symbol: str, data: bytes) -> None:
    out.write(f"static const unsigned char {symbol}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        out.write("    " + "".join(f"0x{b:02x}," for b in chunk) + "\n")
    out.write("};\n\n")


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: embed_vectors.py <vectors_dir> <output.c>\n")
        return 2
    vectors_dir, output = sys.argv[1], sys.argv[2]

    bits = []
    if os.path.isdir(vectors_dir):
        bits = sorted(
            f for f in os.listdir(vectors_dir)
            if f.startswith("testvector") and f.endswith(".bit")
        )

    with open(output, "w") as out:
        out.write("// Generated by embed_vectors.py, do not edit.\n")
        out.write('#include "qemu_vectors.h"\n\n')

        entries = []
        for fname in bits:
            name = fname[:-4]  # strip ".bit"
            symbol = c_symbol(name)
            with open(os.path.join(vectors_dir, fname), "rb") as f:
                data = f.read()
            emit_array(out, symbol, data)
            entries.append((name, symbol, len(data)))

        out.write("const qemu_vector_t QEMU_VECTORS[] = {\n")
        for name, symbol, length in entries:
            out.write(f'    {{"{name}", {symbol}, {length}u}},\n')
        out.write("};\n\n")
        out.write(
            f"const unsigned int QEMU_VECTOR_COUNT = {len(entries)}u;\n"
        )

    sys.stderr.write(
        f"embed_vectors.py: embedded {len(entries)} vector(s) from {vectors_dir}\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
